#!/usr/bin/env python3
"""
AI Documentation Generator for CDC IP Library
---------------------------------------------
This script scans the RTL folder and produces Markdown summaries
for each RTL file. It uses the OpenAI API for human-friendly explanations.
"""

import os
import openai

openai.api_key = os.getenv("OPENAI_API_KEY")

rtl_dir = "rtl"
output_file = "docs/auto_notes.md"

# Make sure output folder exists
os.makedirs("docs", exist_ok=True)

with open(output_file, "w") as f:
    f.write("# 🤖 AI-Generated Notes\n\n")
    f.write("This file is auto-generated by CI on each push.\n\n")

    for file in os.listdir(rtl_dir):
        if file.endswith(".sv"):
            filepath = os.path.join(rtl_dir, file)
            with open(filepath) as src:
                code = src.read()

            prompt = f"Explain in simple terms what this SystemVerilog module does:\n\n{code}\n\n"

            try:
                response = openai.ChatCompletion.create(
                    model="gpt-4o-mini",
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=300
                )
                summary = response.choices[0].message["content"].strip()
            except Exception as e:
                summary = f"(AI doc generation failed: {e})"

            f.write(f"## {file}\n\n{summary}\n\n")

print(f"[AI Doc Gen] Wrote notes to {output_file}")
