name: Smoke Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Dummy build step
        run: echo "CDC IP Library CI: Build OK ✅"
