name: Smoke Test with AI Doc + Log Summaries

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo with full history
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Python and dependencies
      - name: Install Python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install openai

      # Run AI Documentation Generator (all RTL files in rtl/)
      - name: Run AI Documentation Assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 scripts/sdc/ai_doc_gen.py

      # Run AI Log Summarizer (all .log files in logs/)
      - name: Run AI Log Summarizer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 scripts/sdc/ai_log_summarizer.py

      # Commit and push AI-generated docs back
      - name: Commit AI-generated docs back
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add docs/ || true
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Update AI-generated docs [skip ci]"
            git push
          else
            echo "No doc changes to commit."
          fi
